/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package act8baru;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;
/**
 *
 * @author Mourass
 */
public class sisiClient extends javax.swing.JFrame {
    
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    
    /**
     * Creates new form sisiClient
     */
    public sisiClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_pesanserver = new javax.swing.JTextField();
        btn_kirim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        isi_pesanserver = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txt_pesanclient = new javax.swing.JTextField();
        btn_kirimclient = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        isi_pesanclient = new javax.swing.JTextArea();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISI SERVER");

        btn_kirim.setText("KIRIM");
        btn_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimActionPerformed(evt);
            }
        });

        isi_pesanserver.setColumns(20);
        isi_pesanserver.setRows(5);
        jScrollPane1.setViewportView(isi_pesanserver);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chatting Sisi Client");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SISI CLIENT");

        btn_kirimclient.setText("KIRIM");
        btn_kirimclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimclientActionPerformed(evt);
            }
        });

        isi_pesanclient.setColumns(20);
        isi_pesanclient.setRows(5);
        jScrollPane2.setViewportView(isi_pesanclient);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_pesanclient, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_kirimclient)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pesanclient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kirimclient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btn_kirimActionPerformed(java.awt.event.ActionEvent evt) {                                          

    }                                         

    private void btn_kirimclientActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        try {
            String msgout = txt_pesanclient.getText().trim();
            if (msgout.isEmpty() || dout == null) return;

            dout.writeUTF(msgout);  // Kirim ke server
            isi_pesanclient.append("\nMe: " + msgout);  // Tampilkan juga di sisi client
            isi_pesanclient.setCaretPosition(isi_pesanclient.getDocument().getLength());
            txt_pesanclient.setText(""); // Kosongkan field

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengirim pesan!\n" + e.getMessage());
        }
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sisiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sisiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sisiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sisiClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sisiClient().setVisible(true);
            }
        });
        
        try {
            // Minta input dari user
            String ip = JOptionPane.showInputDialog("Masukkan IP Server:", ""); // Ip bisa menggunakan 127.0.0.1 atau 0.0.0.0
            String portStr = JOptionPane.showInputDialog("Masukkan Port Server:", ""); // Nanti masukkan sesuai port di sisiServer atau npm
            String nama = JOptionPane.showInputDialog("Masukkan Nama Anda:");
            if (nama == null || nama.trim().isEmpty()) {
                nama = "User";  // Default nama
            }
            int port = Integer.parseInt(portStr);

            // Koneksi ke server
            s = new Socket(ip, port);
            din = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());

            // Kirim nama ke server duluan
            dout.writeUTF("[NAMA]" + nama);  // Penanda nama

            // Terima pesan dari server
            String pesanmasuk = "";
            while (!pesanmasuk.equals("keluar")) {
                pesanmasuk = din.readUTF();
                isi_pesanclient.append("\nAdmin : " + pesanmasuk);
                isi_pesanclient.setCaretPosition(isi_pesanclient.getDocument().getLength());
            }

        } catch (Exception e) {
            isi_pesanclient.append("\n[ERROR] " + e.getMessage());
            isi_pesanclient.setCaretPosition(isi_pesanclient.getDocument().getLength());
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_kirim;
    private javax.swing.JButton btn_kirimclient;
    private static javax.swing.JTextArea isi_pesanclient;
    private static javax.swing.JTextArea isi_pesanserver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_pesanclient;
    private javax.swing.JTextField txt_pesanserver;
    // End of variables declaration                   
}
